import h5py
import numpy as np
from Terpdose.constants import *
from Terpdose.schema.NittanySchema import *
from Terpdose.utils.genutils import isinstancelist, lbsorted

#  =============
#    XSLibrary  
#  =============

class XSLibrary:
    
    """ The XSLibrary class reads in cross section libraries, potentially
    generated by NittanyPhysics, but not necessarily.
    
    Print an object of this class to view all available attributes.
    
    Parameters
    ----------
    source : str or h5py.Group
        Either the file name corresponding to an HDF5 file output by NittanyPhysics, 
        or the HDF5 group within a Lionbolt HDF5 file that contains an XS library
    
    Examples
    --------
    Access individal CrossSections objects by naming the particles.
    
    Suppose you want to get the scattering cross sections of a particle named 'electrons':
    
    >>> D = XSLibrary('results.h5')
    >>> el = D['electrons']
    >>> # OR
    >>> el = D['electrons', 'electrons']
    
    Suppose you want to get the scattering cross sections for mapping from a particle
    named 'photons' to a particle named 'electrons':
    
    >>> photoelectrons = D['photons', 'electrons']
    
    Attributes
    ----------
    h5 : h5py.File or h5py.Group
        Either the full HDF5 file or just the group depending on how the object 
        was initialized.
    num_materials : int
        Number of materials described by this library.
    present_particles : list(str)
        Names of particles described by this library.
    <self[p1, p2]> : CrossSections
        For a provided p1 (str) and p2 (str) which give particle names, gives
        the CrossSections object corresponding to the mapping from p1 to p2.
        If p1 = p2 then one can use either [p1, p1] or [p1] and get single-particle
        cross sections.
    """
    
    def __init__ (self, source):
        
        if isinstance(source, str):
            self.h5      = h5py.File(source, 'r')
            self._ownsh5 = True
        elif isinstance(source, (h5py.File, h5py.Group)):
            self.h5      = source
            self._ownsh5 = False
        else:
            raise TypeError ('PhysicsClasses.py: XSLibrary: source argument must be an h5 file or a string pointing to an h5 file location.')
        
        self._data = {}
        
        self.num_materials     = self._get_num_materials ()
        self.present_particles = self._get_present_particles ()
        
        for inc in self.present_particles:
            self._data.setdefault(inc, {})
            for out in self.present_particles:
                self._data[inc].setdefault(out, None)
                
                self._FormTransfer (inc, out)
    
    def __getitem__ (self, particles):
        # Returns the requested object using ['p1', 'p2'].obj
        # If only ['p1'] is given returns ['p1', 'p1']
        if isinstance(particles, (tuple, list)):
            d = self._data
            for p in particles:
                d = d[p]
            return d
        else:
            return self._data[particles][particles]
    
    def _get_num_materials (self):
        return self.h5.attrs[ATTR_NUMMATS][()]
    
    def _get_present_particles (self):
        
        # Determine the set of particles present in the library.
        # 
        # This function does so by looping over the pattern and numbering from 1 to 
        # however many particles there are.
        # As soon as it fails to find a consecutive particle, it returns
        
        p = []
        
        finished = False
        ip = 0
        while not finished:
            ip = ip + 1
            
            try:
                p.append(self.h5.attrs[f'{ATTR_PRTCLNAMES}{PATTERN_PNUM}{ip}'].decode('utf-8'))
            except:
                finished = True
        
        return p
    
    def _FormTransfer (self, p1, p2):
        
        group = f'{p1}{PATTERN_IN}{p2}{PATTERN_OUT}'
        
        if group in sorted(self.h5.keys()):
            self._data[p1][p2] = CrossSections (p1, p2, self)
    
    def destroy (self):
        
        """ Deallocates all data 
        """
        
        delattr (self, h5)
        delattr (self, _ownsh5)
        delattr (self, num_materials)
        for p1 in self.present_particles:
            for p2 in self.present_particles:
                self[p1, p2].destroy()
        
        delattr (self, present_particles)
        delattr (self, _data)
    
    def __repr__ (self):
        
        # Lists all available data. Access by printing the object.
        
        from Terpdose.utils.genutils import generic_repr
        
        return generic_repr (self)

class CrossSections:
    
    """ Reads and holds the cross sections for a choice of incident and outgoing particles
    
    Parameters
    ----------
    p1 : str
        Incident particle name according to the HDF5 file.
    p2 : str
        Outgoing particle name according to the HDF5 file.
    parent : XSLibrary
        The parent XSLibrary from which these cross sections are pulled.
    
    Attributes
    ----------
    h5 : h5py.Group
        The group within the HDF5 file describing this p1, p2
    scattering : list(np.float64 [:,:,:])
        The scattering cross sections in units of cm^{-1}. The list is over outgoing energy indices,
        while the ranks are [material, Legendre order, incident energy index]
    attn : np.float64 [:,:]
        p1 = p2 only. The attenuation coefficients in units of cm^{-1}. Ranks are [material, energy index]
    energy_dep : np.float64 [:,:]
        p1 = p2 only. The energy deposition coefficients in units of MeV / cm. Ranks are [material, energy index]
    dose_dep : np.float64 [:,:]
        p1 = p2 only. The dose deposition coefficients in units of MeV * cm^{2} / g. Ranks are [material, energy index]
    charge_dep : np.float64 [:,:]
        p1 = p2 only. The charge deposition coefficients in units of e / cm. Ranks are [material, energy index]
    """
    
    def __init__ (self, p1, p2, parent : XSLibrary):
        self._parent  = parent
        
        group = f'{p1}{PATTERN_IN}{p2}{PATTERN_OUT}'
        
        self.h5 = self._parent.h5[group] # Inefficient?
        
        if p1 == p2:
            self.scattering = self._get_scattering (coupling=False)
            self.attn       = self._get_attn       ()
            self.energy_dep = self._get_energy_dep ()
            self.dose_dep   = self._get_dose_dep   ()
            self.charge_dep = self._get_charge_dep ()
        else:
            self.scattering = self._get_scattering (coupling=True)
    
    def _read_single (self, subgroup):
        
        ''' Reads the multigroup moments of an --------- '''
        ''' MUST NOTE ITS [m,g] '''
        
        gkeys = lbsorted(self.h5.keys())
        
        G = len(gkeys)
        
        Nm = self._parent.num_materials
        
        arr = np.zeros((Nm, G), dtype=np.float64)
        
        for g_ind in range(G):
            
            gstr = gkeys[g_ind]
            
            arr[:,g_ind] = self.h5[f'{gstr}/{subgroup}'][()]
        
        return arr
    
    def _get_scattering (self, coupling):
        
        ''' MUST NOTE ITS [m, ell, g_in] '''
        
        gkeys = lbsorted(self.h5.keys())
        
        ellkeys = lbsorted(self.h5[f'{gkeys[0]}/{GROUP_SCATTER}'].keys())
        
        G_out = len(gkeys) # Since this is based on these keys, this is G_out
        
        L = len(ellkeys) - 1
        
        Nm = self._parent.num_materials
        
        if not coupling:
            arr = [ np.zeros((Nm, L + 1, g_out + 1), dtype=np.float64)
                      for g_out in range(G_out) ]
        else:
            # Coupling cross sections do not have a strict relationship
            # between g_in and g_out, thus between G_in and G_out.
            G_in  = len(self.h5[f'{gkeys[0]}/{GROUP_SCATTER}/{ellkeys[0]}'][()][0,:])
            # G_in  = len(self.h5[f'{gkeys[-1]}/{GROUP_SCATTER}/{ellkeys[0]}'][()][0,:])
            
            arr = [ np.zeros((Nm, L + 1, G_in), dtype=np.float64)
                      for g_out in range(G_out) ]
        
        for g_out in range(G_out):
            
            gstr = gkeys[g_out]
            
            for ell in range(L+1):
                
                ellstr = ellkeys[ell]
                if Nm == 1:
                    arr[g_out][0, ell, :] = self.h5[f'{gstr}/{GROUP_SCATTER}/{ellstr}'][()]
                    # tmp = self.h5[f'{gstr}/{GROUP_SCATTER}/{ellstr}'][()]
                    # arr[g_out][0, ell, 0:len(tmp[0])] = tmp[0]
                else:
                    arr[g_out][:, ell, :] = self.h5[f'{gstr}/{GROUP_SCATTER}/{ellstr}'][()]
        
        return arr
    
    def _get_attn (self):
        return self._read_single (DATASET_ATTN)
    
    def _get_energy_dep (self):
        return self._read_single (DATASET_EDXS)
    
    def _get_dose_dep (self):
        return self._read_single (DATASET_DDXS)
    
    def _get_charge_dep (self):
        return self._read_single (DATASET_CDXS)
    
    def destroy (self):
        
        """ Deallocates all data 
        """
        
        delattr (self, _parent)
        delattr (self, h5)
        delattr (self, scattering)
        if hasattr (self, attn):
            delattr (self, attn)
        if hasattr (self, energy_dep):
            delattr (self, energy_dep)
        if hasattr (self, dose_dep):
            delattr (self, dose_dep)
        if hasattr (self, charge_dep):
            delattr (self, charge_dep)
    
    def __repr__ (self):
        
        # Lists all available data. Access by printing the object.
        
        from Terpdose.utils.genutils import generic_repr
        
        return generic_repr (self)